apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1dg8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-1dg8@sha256:ccce088f68cb08d9a2f4f12b2eeaa571176f9d25eebd69826b0d111ab0693b2f
        name: my-nodejs
        resources: {}
status: {}
